name: Run Data Sync

on:
  workflow_dispatch: 

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      id: setup_python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: 'requirements.txt'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run sync Nike script
      env:
        WR_VID: ${{ secrets.WR_VID }}
        WR_SKEY: ${{ secrets.WR_SKEY }}
      run: python run.py

    - name: Pushes test folder
      uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'books'
        destination_repo: 'wjianbo/my-ob-vault'
        destination_branch: 'main'
        destination_folder: 'blog-content/books'
        user_email: 'jnb.wang@gmail.com'
        user_name: 'wjianbo'
        commit_msg: '[GHA] Update blog contents.'
